# Generated by Django 5.2.1 on 2025-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userprofile_delete_mainuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
